# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7eaa2eb66230052fe0306885c61429f5ec3a8cc0ed2d8705210d17086498eb7d1f371e9d8a145a2ca226f884d314a70f2c45fa23f47cb17b813ea7207928e604

test:
  secret_key_base: 490159cf8ca6c5e5f556dcbbb1319828616cb0a879ff1fd098c7d823b49cdba44021aadafd799eb64b9161b71982940a8c28f800e1975d205cdcfea7dc9f2c86

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
